/* ----------------------------------------------------------- */
/* WARNING: NOT MODIFY THIS FILE */
/* ----------------------------------------------------------- */
/* Step 1: Modify file color-preview.json */
/* Step 2: npm run gen-color */
/* ----------------------------------------------------------- */

export type TColor =
  | 'white'
  | 'black'
  | 'primary-gray'
  | 'primary-lighter'
  | 'primary-light'
  | 'primary-main'
  | 'primary-dark'
  | 'primary-darker'
  | 'primary-black'
  | 'primary-main-q'
  | 'primary-lightest'
  | 'secondary-lightest'
  | 'secondary-lighter'
  | 'secondary-light'
  | 'secondary-main'
  | 'secondary-dark'
  | 'secondary-primary'
  | 'neutral-white'
  | 'neutral-gray-2'
  | 'neutral-gray-3'
  | 'neutral-gray-4'
  | 'neutral-gray-5'
  | 'neutral-gray-6'
  | 'neutral-gray-7'
  | 'neutral-gray-8'
  | 'neutral-gray-9'
  | 'neutral-gray-10'
  | 'neutral-darker'
  | 'success-background'
  | 'success-hover'
  | 'success-main'
  | 'success-active'
  | 'warning-background'
  | 'warning-hover'
  | 'warning-main'
  | 'warning-active'
  | 'error-background'
  | 'error-hover'
  | 'error-main'
  | 'error-active'
  | 'link-1'
  | 'link-2'
  | 'link-3'
  | 'link-4'
  | 'link-5'
  | 'text-primary'
  | 'text-secondary'
  | 'primary-8-percent'
  | 'editor-main';
